/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#b3b0bc",
        "primary": "#4e4bd5",
        "secondary-fixed": "#d3e4fe",
        "secondary-dim": "#44546a",
        "primary-container": "#7472fd",
        "tertiary-container": "#fcd2fe",
        "on-secondary-fixed": "#314055",
        "surface-variant": "#e4e1ed",
        "on-background": "#32313b",
        "primary-fixed-dim": "#6765ef",
        "on-primary": "#fbf7ff",
        "inverse-primary": "#8382ff",
        "on-tertiary-fixed": "#513355",
        "tertiary": "#755478",
        "error-container": "#f97386",
        "tertiary-fixed-dim": "#eec4ef",
        "surface-container": "#f0ecf6",
        "on-primary-fixed-variant": "#020027",
        "error": "#a8364b",
        "surface-dim": "#dbd8e4",
        "on-primary-container": "#000000",
        "error-dim": "#6b0221",
        "on-secondary-fixed-variant": "#4d5d73",
        "on-surface": "#32313b",
        "secondary-fixed-dim": "#c5d6f0",
        "surface-tint": "#4e4bd5",
        "secondary-container": "#d3e4fe",
        "on-secondary": "#f7f9ff",
        "surface-container-low": "#f6f2fa",
        "surface-container-highest": "#e4e1ed",
        "inverse-surface": "#0e0e12",
        "tertiary-fixed": "#fcd2fe",
        "inverse-on-surface": "#9e9ca2",
        "on-tertiary": "#fff7fa",
        "primary-fixed": "#7472fd",
        "on-tertiary-fixed-variant": "#6f4e73",
        "surface-container-lowest": "#ffffff",
        "on-error": "#fff7f7",
        "surface-bright": "#fcf8fe",
        "surface": "#fcf8fe",
        "outline": "#7b7984",
        "tertiary-dim": "#68486c",
        "on-tertiary-container": "#654569",
        "on-primary-fixed": "#000000",
        "background": "#fcf8fe",
        "primary-dim": "#413dc9",
        "on-secondary-container": "#435368",
        "secondary": "#506076",
        "surface-container-high": "#eae6f1",
        "on-error-container": "#6e0523",
        "on-surface-variant": "#5f5e68"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
