name: Build and Cross-Browser Test
on: [push]

jobs:
  devops-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: echo "Infrastruktur siap."

      - name: Docker Validation
        run: docker compose build